[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.100.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_BUILD_DRAFTS = "false"
  HUGO_BUILD_FUTURE = "false"
  HUGO_BUILD_EXPIRED = "false"

# Sitemap
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# RSS Feed
[[redirects]]
  from = "/index.xml"
  to = "/index.xml"
  status = 200